Feature/hyperparameter tuning
TUDB-Labs/mLoRA pull request #266
Opened 2024-10-25 20:52 UTC by Saf9933

**added mlora_train_optuna.py script** 

- Passed all local tests.
- Code quality checks with flake8.
- Isolated changes to only include mlora_train_optuna.py.

2024-10-26 00:53 UTC, merlintang commented
can we have a design doc for this pr, meanwhile, why we need to change lots of configuration in the training model

2024-10-26 08:40 UTC, Saf9933 commented
> can we have a design doc for this pr, meanwhile, why we need to change lots of configuration in the training model

I've added a design to the PR description to outline the changes. Regarding the configuration changes, they were necessary to enable hyperparameter tuning using Optuna. This tuning process allows key training parameters such as learning rate, rank, alpha, and dropout to be optimized dynamically rather than being fixed. The goal was to improve the model's performance by letting the tuning process find the optimal configuration for each training trial automatically, thus adding flexibility to the training pipeline.

2024-10-28 02:10 UTC, yezhengmao1 requested changes
do not use your local format tool to format files. can not pass the CI.

2024-10-28 02:10 UTC, yezhengmao1 commented on mlora_train.py
do not modify this file.

2024-10-28 02:10 UTC, yezhengmao1 commented on mlora/model/llm/model_llama.py
do not modify this file.

2024-10-28 02:15 UTC, yezhengmao1 commented
can you just only add a new file : mlora_train_optuna.py

2024-10-29 08:42 UTC, closed without merging